### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by samqin123** [BenedictKing/chinesepua#3]
[INFO][2024-09-19 12:37:53][ntchat_channel.py:272] - [WX] sendMsg=Reply(type=TEXT, content=[AI-xiaoyibao] 卡片生成中...), receiver=qinxiaoqiang2002
[ERROR][2024-09-19 12:37:59][chinesepua.py:222] - HTML渲染为图片失败: Object of type BytesIO is not JSON serializable
[INFO][2024-09-19 12:37:59][ntchat_channel.py:276] - [WX] sendMsg=Reply(type=ERROR, content=生成卡片失败，请稍后再试。。。), receiver=qinxiaoqiang2002

环境：
1. config.json中配置的是moonshot的api和key, 看文档中并没有限制必须用openai 或者 claude；
2. 我用的是ntchat

请大神看下。

**Comment by samqin123** [comment]
<img width="1757" alt="image" src="https://github.com/user-attachments/assets/8db99fe7-4b0a-477c-bb06-1ffc07a25d19">
重新部署了cow，原版克隆，没有修改任何文件，模型换成gpt4o-mini，还是不行

**Comment by BenedictKing** [comment]
cow开debug模式，看看输出的html或者svg代码是否完整，可能的解决办法是配置中的max_tokens改为4096

**Comment by BenedictKing** [comment]
> <img alt="image" width="1757" src="https://private-user-images.githubusercontent.com/103937568/368862177-8db99fe7-4b0a-477c-bb06-1ffc07a25d19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDU4MjEsIm5iZiI6MTcyNjgwNTUyMSwicGF0aCI6Ii8xMDM5Mzc1NjgvMzY4ODYyMTc3LThkYjk5ZmU3LTRiMGEtNDc3Yy1iYjA2LTFmZmMwN2EyNWQxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNDEyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjAzYTM1NGJhZDkwYmFkNjcyZmNkZTk3YTdjYjRjNTFmMDkzNTBmN2M2NjNkMTY2ZGQxMzdmM2RiYWIyYmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Yag53n6s280Pu-FKJsXtGBhGYVGyEzBBBF4d8YVS0wU"> 重新部署了cow，原版克隆，没有修改任何文件，模型换成gpt4o-mini，还是不行

看报错是没有装chromium，跟模型无关

**Comment by samqin123** [comment]
原因找到了，是我用的cow ntchat协议，其中channel文件修改了，换用cow原生的itchat版本，都正常了。测试模型gpt-4o-mini可以用，其它模型没试过。建议补充下推荐模型。
